# Generated by Django 2.1.5 on 2019-04-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_auto_20190421_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('disapproved', 'Disapproved'), ('pending', 'Pending')], max_length=20)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='beneficiary.Beneficiary')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('beneficiary', 'month', 'year')},
        ),
    ]
