# Generated by Django 2.1.5 on 2019-04-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0005_auto_20190421_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('beneficiary', 'month', 'year', 'status')},
        ),
    ]
