# Generated by Django 2.1.5 on 2019-04-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0006_auto_20190421_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempapproved', to='beneficiary.Beneficiary')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('beneficiary', 'month', 'year')},
        ),
    ]
