# Generated by Django 2.1.5 on 2019-04-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_auto_20190421_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('phone_num', models.PositiveIntegerField()),
                ('account_number', models.PositiveIntegerField()),
                ('ifsc_code', models.CharField(max_length=50)),
                ('is_approved_rent', models.BooleanField(default=False)),
                ('is_approved_clerk', models.BooleanField(default=False)),
                ('is_approved_adc', models.BooleanField(default=False)),
                ('is_disapproved', models.BooleanField(default=False)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='beneficiary.Scheme')),
            ],
        ),
    ]
