# Generated by Django 2.1.5 on 2019-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0008_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone_num',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
